apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: test2
kubeconfigPath: /tmp/test2
nodes:
- role: control-plane
  extraMounts:
  - hostPath: "./.github/config/seccomp-profiles"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
networking:
  disableDefaultCNI: true
  podSubnet: "10.2.0.0/16"
  serviceSubnet: "172.20.2.0/24"
