apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.30.2
  extraMounts:
  - hostPath: "./.github/config/seccomp-profiles"
    containerPath: "/var/lib/kubelet/seccomp/profiles"
networking:
  disableDefaultCNI: true
  podSubnet: "10.1.0.0/16"
  serviceSubnet: "172.20.1.0/24"
