# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
        with:
          version: latest

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

  # Run acceptance tests in a matrix with Terraform CLI versions
  test-tofu:
    name: Opentofu Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever tofu versions here you would like to support
        tofu:
          - '1.6.*'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.tofu }}
          tofu_wrapper: false
      - name: Setup kind
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config.yaml
      - run: go mod download
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./cilium
        timeout-minutes: 10

  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - '1.5.*'
          - '1.6.*'
          - '1.7.*'
          - '1.8.*'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # v3.1.0
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - name: Setup kind
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config.yaml
      - run: go mod download
      - env:
          TF_ACC: "1"
        run: go test -v -cover ./cilium
        timeout-minutes: 10

  test-cluster-mesh:
    name: "Functionnal test: Clustermesh"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever tofu versions here you would like to support
        tofu:
          - '1.6.*'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.tofu }}
          tofu_wrapper: true
      - name: Setup kind test1
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config.yaml
          cluster_name: "test1"
      - name: Setup kind test2
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config2.yaml
          cluster_name: "test2"
      - run: make
      - run: cp .github/tf/versions.tf .github/tf/clustermesh
      - run: tofu init
        working-directory: .github/tf/clustermesh
      - run: tofu apply -auto-approve
        working-directory: .github/tf/clustermesh
      - run: tofu destroy -auto-approve
        working-directory: .github/tf/clustermesh

  test-kubeproxy-free:
    name: "Functionnal test: kubeproxy-free"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever tofu versions here you would like to support
        tofu:
          - '1.6.*'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.tofu }}
          tofu_wrapper: true
      - name: Setup kind test1
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config.yaml
          cluster_name: "test1"
      - run: make
      - run: cp .github/tf/versions.tf .github/tf/kubeproxy-free
      - run: tofu init
        working-directory: .github/tf/kubeproxy-free
      - run: tofu apply -auto-approve
        working-directory: .github/tf/kubeproxy-free
      - run: kubectl get ds/kube-proxy -n kube-system -o jsonpath='{.status.currentNumberScheduled}' | grep -q 0
      - run: tofu destroy -auto-approve
        working-directory: .github/tf/kubeproxy-free

  test-cilium-install:
    name: "Functionnal test: cilium-install"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        # list whatever tofu versions here you would like to support
        tofu:
          - '1.6.*'
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.tofu }}
          tofu_wrapper: true
      - name: Setup kind test1
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        with:
          wait: 0
          config: .github/config/acceptance_tests_kind_config.yaml
          cluster_name: "test1"
      - run: make
      - run: cp .github/tf/versions.tf .github/tf/cilium/
      - run: kubectl create namespace cilium
      - run: tofu init
        working-directory: .github/tf/cilium
      - run: tofu apply -auto-approve
        working-directory: .github/tf/cilium
      - run: kubectl get pod -n cilium
      - run: tofu destroy -auto-approve
        working-directory: .github/tf/cilium
      - run: kubectl get pod -n cilium
